In [1]:
from metaflow import Flow, get_metadata

print("Current metadata provider: %s" % get_metadata())

Current metadata provider: local@/Users/sonoffungdark/Projects/merchantizer/merchantizer

### What happened in model.py?
The code generated embeddings in preparation for the BERT topic modeling task. It then goes into the model fitting step, leveraging a sample of the cleaned description data.

In [2]:
run = Flow('MerchantModelFlow').latest_successful_run
print("Using run: %s" % str(run))

topic_info_df = run.data.topic_info_df

Using run: Run('MerchantModelFlow/1714402285381590')

### Topic Model Report
Let's first take a look at the specified topics. The first 24 were specified in the code, and the following (those Names prepended by a number) are what the model found as topics on its own. An example is topic 25. When you look at the Representation_Docs column for it, it appears to be honing in on grocery patterns.

In [3]:
topic_info_df

,Topic,Count,Name,Representation,Representative_Docs
0,0,11413,walmart,"[mart, wal, supermarket, stores, grocery, stor...","[wal-mart mart , wal-mart mart , wal-mart mart ]"
1,1,6592,cashapp,"[cashapp, cash, adoordash, apple, paymentoast,...","[apple cash balance adoordash , apple cash bal..."
2,2,5070,mcdonalds,"[mcdonalds, burgers, burger, kfc, dunkin, frys...","[burger-king, mcdonalds, mcdonalds]"
3,3,3124,uber,"[uber, trip, help, ride, transit, postmates, t...","[uber trip help.uber , uber tri..."
4,4,2430,starbucks,"[starbucks, cafe, 800, kroger, coffee, 782, ba...","[starbucks 800-782-7282, starbucks 800-782-728..."
5,5,2318,apple,"[apple, caus, bill, ca, mac, macs, mous, 7733,...","[apple /bill 866-712-7753 caus, apple ..."
6,6,2260,7-eleven,"[seven, eleven, 7th, 7eleven, 7eletxus, 11, 07...","[7-eleven, 7-eleven, 7-eleven]"
7,7,2260,amazon,"[mktp, amazon, us, netflix, paypal, kindle, bi...","[amazon mktp us, amazon mktp us am..."
8,8,2060,taco-bell,"[tacobell, taco, tacos, bell, tasty, bells, do...","[doordash*taco-bell www.doordash.caus, doo..."
9,9,1973,doordash,"[doordash, mcdonalds, doordashdashpass, caus, ...",[doordash doordash mcdonalds 855-973-1040 ca...
10,10,1922,google,"[google, caus, storage, gaus, ca, helppay, gbr...","[google *google storage 855-836-3987 caus, goo..."
11,11,1917,365-market,"[market, market32, mymarketrewards, marketplac...","[365-market j 888 432-3, 365-market j 888 432-..."
12,12,1571,shell,"[shell, portland, puff, bay, beach, playstatio...","[shell, shell, shell]"
13,13,1552,dollar-general,"[dollar, dollartre, generaln, generalnera, gen...","[dollar-general market place, dollar-general d..."
14,14,1551,circle-k,"[circle, 01344, k1, 09528, 01590, 23378, 01677...","[circle-k # 01344, circle 1 market , cir..."
15,15,1391,square,"[square, quickquack, gosquare, corner, queens,...","[square *square weebly, square inc., square..."
16,16,1283,lyft,"[lyft, 5pm, ride, 4pm, rides, caus, fri, 5am, ...","[lyft ride tue 4pm 855-865-9553 caus, lyf..."
17,17,1125,chevron,"[chevron, petrol, gasoline, petroleum, chegg, ...","[chevron gas station , chevron, chevron g..."
18,18,1034,wendys,"[wendys, wendy, dennys, krispy, hortons, daves...","[wendys, wendys, wendys]"
19,19,992,exxon,"[exxon, exxonmobil, petroleum, oil, expres, fu...","[bell exxon, exxon food mart , exxon t-s..."
20,20,879,toast,"[toast, toasted, bread, sandwich, snack, loaf,...","[toast * taco taco, toast * toast fine food & ..."
21,21,758,family-dollar,"[dollar, family, cousins, coin, dads, goodwill...","[family-dollar #, family-dollar #, family-doll..."
22,22,715,target,"[target, hit, shooting, mart, goodstop, store,...","[target *, target * , target *]"
23,23,615,dollar-tree,"[dollartree, dollar, dollartre, tree, billingt...","[dollar-tree, dollar-tree, dollar-tree]"
24,24,27498,-1_ca_caus_dave_angeles,"[ca, caus, dave, angeles, playstation, txus, i...","[playstation network 800-345-7669 caus, dav..."
25,25,1480,0_grocery_atlanta_food_foods,"[grocery, atlanta, food, foods, grocers, super...","[j&b food mart monroe gaus, foo..."
26,26,1069,1_flus_miami_fl_florida,"[flus, miami, fl, florida, cmsvend, tampa, jac...","[cmsvend*cv miami miami flus, spe..."
27,27,809,2_liquors_liquor_beverage_bourbon,"[liquors, liquor, beverage, bourbon, beverages...","[t liquor, r s liquor , j&j liquor]"
28,28,722,3_smokeshop_smokehouse_smokes_smoke,"[smokeshop, smokehouse, smokes, smoke, smoker,...","[smoke shop, smoke shop, smoke shop]"
29,29,718,4_chicago_ilus_mius_detroit,"[chicago, ilus, mius, detroit, il, mi, wius, m...","[bp#9404930north ave bp chicago ilus, bp#..."

### View Predictions Across 3 Important Merchants

In [4]:
fit_prediction_df = run.data.fit_prediction_df

In [5]:
fit_prediction_df[fit_prediction_df["cleaned_description"].str.contains("target")]

,merchantName,description,cleaned_description,pruned_description,predicted_topic,predicted_merchant
1324612,NaN,TARGET 00008151 FORT LAUDERDAFLUS,target 00008151 fort lauderdaflus,target,22,target
1475940,NaN,TARGET 00018226 CLIFTON NJUS,target 00018226 clifton njus,target,22,target
1370972,NaN,TARGET 00022459 ONTARIO CAUS,target 00022459 ontario caus,target,22,target
1127934,TARGET 00007567,TARGET 00007567,target 00007567,target,22,target
2773579,TARGET T- 855 E Birch,TARGET T- 855 E Birch,target t- 855 e birch,target,22,target
...,...,...,...,...,...,...
865349,NaN,TARGET T- 16806 N 7th Phoenix AZ,target t- 16806 n 7th phoenix az,target,22,target
7259809,TARGET 00023457,TARGET 00023457,target 00023457,target,22,target
8870552,TARGET 00010074,TARGET 00010074,target 00010074,target,22,target
6958731,TARGET 00020420,TARGET 00020420,target 00020420,target,22,target
8783486,TARGET 00011726,TARGET 00011726,target 00011726,target,22,target

In [6]:
fit_prediction_df[fit_prediction_df["cleaned_description"].str.contains("doordash")]

,merchantName,description,cleaned_description,pruned_description,predicted_topic,predicted_merchant
9059513,DD DOORDASH SHARKSFIS,DD DOORDASH SHARKSFIS,doordash doordash sharksfis,doordash,9,doordash
3359018,NaN,DD *DOORDASH PETSMART SAN FRANCISCO CA,doordash *doordash petoast mart san francisc...,doordash,9,doordash
8162999,CASH APP*GILLIS*ADD,CASH APP*GILLIS*ADD,cashapp *gillis*adoordash,cashapp,1,cashapp
1120582,DD/BR #304762 Q35,DD/BR #304762 Q35,doordash /br #304762 q35,doordash,9,doordash
3582987,NaN,DOORDASH*AUNTIE ANNES WWW.DOORDASH.CAUS,doordash*auntie annes www.doordash.caus,doordash*auntie annes www.doordash.caus,9,doordash
...,...,...,...,...,...,...
3832407,GETISLANDDREAMSDISCOUN,GETISLANDDREAMSDISCOUN,getislandoordash,getislandoordash,9,doordash
2036127,NaN,DD DOORDASH LITTLECAE 855-973-1040 CAUS,doordash doordash littlecae 855-973-1040 caus,doordash,9,doordash
7258987,DD DOORDASH OHFISHSUS,DD DOORDASH OHFISHSUS,doordash doordash ohfishsus,doordash,9,doordash
5969347,NaN,DD DOORDASH PANDAEXPR 855-973-1040 CAUS,doordash doordash pandaexpr 855-973-1040 caus,doordash,9,doordash
7186902,NaN,DD DOORDASH DASHMART 855-973-1040 CAUS,doordash doordash dashmart 855-973-1040 caus,doordash,9,doordash

In [7]:
fit_prediction_df[fit_prediction_df["cleaned_description"].str.contains("amazon")]

,merchantName,description,cleaned_description,pruned_description,predicted_topic,predicted_merchant
2134722,Amazon Prime*TO5QL1NO2,Amazon Prime*TO5QL1NO2,amazon prime*to5ql1no2,amazon,7,amazon
3481542,NaN,GOOGLE *Amazon Mobile 855-836-3987 CAUS,google *amazon mobile 855-836-3987 caus,google,7,amazon
4058636,AMAZON.COM*JZ20R4EC3,AMAZON.COM*JZ20R4EC3,amazon *jz20r4ec3,amazon,7,amazon
3988415,NaN,AMZN Mktp US*J885B3L43 Amzn.com/billWAUS,amazon mktp us*j885b3l43 amazon /billwaus,amazon,7,amazon
6260500,NaN,AMZN Mktp US*TP3KV8UF2 Amzn.com/billWAUS,amazon mktp us*tp3kv8uf2 amazon /billwaus,amazon,7,amazon
...,...,...,...,...,...,...
2838281,AMZN Mktp US*E57T75SB3,AMZN Mktp US*E57T75SB3,amazon mktp us*e57t75sb3,amazon,7,amazon
2206441,NaN,Amazon Prime*ET9S17TC3 Amzn.com/billWAUS,amazon prime*et9s17tc3 amazon /billwaus,amazon,7,amazon
4484013,NaN,AMZN Mktp US*SM9UA8ZV3 Amzn.com/billWAUS,amazon mktp us*sm9ua8zv3 amazon /billwaus,amazon,7,amazon
7691322,NaN,AMZN Mktp US*S74AC7463 Amzn.com/billWAUS,amazon mktp us*s74ac7463 amazon /billwaus,amazon,7,amazon
9187291,NaN,Audible*OG6HQ3J33 Amzn.com/billNJUS,audible*og6hq3j33 amazon /billnjus,audible*og6hq3j33 amazon /billnjus,7,amazon

### Notable Issues/Key Concerns
* Again, we see the doordashxcashapp problem rearing its ugly head. We had already addressed this with a TODO in the clean.py file, so that could be sorted in the future. I would recommend an investigation on multi-merchant descriptions.
* I would also consider looking into stopgap words that exist in merchant names. 365 Market is a good example, the results would likely be better if Market was removed from the 365 descriptions, thereby creating seperation between it and all the other market descriptions.
* My biggest concern was how computationally costly the bertopic package was. I had to downsample to 100 thousand from 10 million. About halfway through my task, I spun up a large GPU in the cloud and began running the same code with 1 million records. It is still running (~3 hours in). I would recommend an investigation into various strategies that could be leveraged (GPU acceleration, for example), to improve the compute time.